// Pure data file (no <script> tags). Shared by learn.html and alphabet.html.
window.AI_DATA = {
  "A": { "word": "ALGORITHM", "definition": "A set of steps to solve a problem.", "todo": "Write steps to brush your teeth like a robot would.", "remember": "Algorithms are recipes for computers.", "image": null },
  "B": { "word": "BOT", "definition": "A program that chats or helps you.", "todo": "List 3 helpful things a school bot could do.", "remember": "Bots follow rules written by people.", "image": null },
  "C": { "word": "CODE", "definition": "Instructions that tell a computer what to do.", "todo": "Write five ‘if this, then that’ rules for a game.", "remember": "Good code is clear and kind to future readers.", "image": null },
  "D": { "word": "DATA", "definition": "Facts, numbers, and words that computers use.", "todo": "Collect class shoe sizes and find the most common.", "remember": "More data can mean better answers—if it’s good data.", "image": null },
  "E": { "word": "ETHICS", "definition": "Knowing right from wrong in tech use.", "todo": "Write a ‘fair use’ rule for class devices.", "remember": "Ask: Is it fair? Is it safe? Does it help others?", "image": null },
  "F": { "word": "FAKE", "definition": "Something that looks real but isn’t.", "todo": "Compare two photos and spot clues that one is fake.", "remember": "Check with a trusted person or source.", "image": null },
  "G": { "word": "GLITCH", "definition": "A small error that makes things act weird.", "todo": "Describe a funny glitch you’ve seen and how to fix it.", "remember": "Bugs happen; we test, fix, and learn.", "image": null },
  "H": { "word": "HALLUCINATION", "definition": "When AI makes up something untrue.", "todo": "Write two truths and one made‑up ‘AI fact’.", "remember": "Verify important info with reliable sources.", "image": null },
  "I": { "word": "INTERNET", "definition": "A giant network that connects computers.", "todo": "Sketch a map of how your device reaches a website.", "remember": "Be kind and careful when you’re online.", "image": null },
  "J": { "word": "JUDGEMENT", "definition": "Using good sense to decide what’s best.", "todo": "Create a class rule for good digital judgement.", "remember": "People—not apps—make final choices.", "image": null },
  "K": { "word": "KEYWORD", "definition": "An important word you search for.", "todo": "Pick better keywords for a tricky question.", "remember": "Specific keywords find better results.", "image": null },
  "L": { "word": "LITERACY", "definition": "Understanding and using information well.", "todo": "Explain a tech word to a younger student.", "remember": "We learn by reading, doing, and teaching.", "image": null },
  "M": { "word": "MACHINE LEARNING", "definition": "When computers find patterns in data.", "todo": "Group animal cards by features to ‘train’ a model.", "remember": "Machines learn from examples we give them.", "image": null },
  "N": { "word": "NEURAL NETWORK", "definition": "A layered system that learns patterns.", "todo": "Draw dots (neurons) and lines (connections).", "remember": "It’s inspired by brains, but it isn’t a brain.", "image": null },
  "O": { "word": "OBJECT SPOTTER", "definition": "A tool that finds things in pictures.", "todo": "Circle all the triangles you can find in the room.", "remember": "Cameras need clear, fair training images.", "image": null },
  "P": { "word": "PROMPT", "definition": "The message you give an AI to start a task.", "todo": "Write a prompt, then improve it twice.", "remember": "Clear prompts lead to better results.", "image": null },
  "Q": { "word": "QUERY", "definition": "A question you ask a computer.", "todo": "Turn a big question into three smaller queries.", "remember": "Good queries are short and specific.", "image": null },
  "R": { "word": "ROBOT", "definition": "A machine that can sense, think, and act.", "todo": "Act like a ‘robot’ using only three commands.", "remember": "Robots help people; people lead.", "image": null },
  "S": { "word": "SIRI", "definition": "An example of a voice assistant.", "todo": "List three things a voice assistant can do safely.", "remember": "Assistants listen for commands; use them kindly.", "image": null },
  "T": { "word": "TURING TEST", "definition": "A game: can you tell machine from human?", "todo": "Write three questions to tell them apart.", "remember": "Being useful matters more than ‘passing’.", "image": null },
  "U": { "word": "UNPLUG", "definition": "Take a break from screens.", "todo": "Plan a 10‑minute unplugged activity.", "remember": "Our minds need rest to learn well.", "image": null },
  "V": { "word": "VOICE RECOGNITION", "definition": "Tech that understands speech.", "todo": "Say a tongue‑twister—how might a computer hear it?", "remember": "Background noise and accents matter.", "image": null },
  "W": { "word": "WI‑FI", "definition": "Wireless internet connection.", "todo": "Draw your home or school network as a map.", "remember": "Never share passwords publicly.", "image": null },
  "X": { "word": "eXPLORATION", "definition": "Trying new ideas to learn.", "todo": "Explore a new app and write three tips.", "remember": "Curiosity + care = discovery.", "image": null },
  "Y": { "word": "YOU", "definition": "The most important decision‑maker.", "todo": "Write your tech promise to your future self.", "remember": "Use tech to help people and planet.", "image": null },
  "Z": { "word": "ZEROES & ONES", "definition": "Binary digits computers use.", "todo": "Make a bracelet pattern using 0s and 1s.", "remember": "Big ideas start with tiny bits.", "image": null }
};
